## Site settings
# title, shows up in browser title bar
title: Your First Pull Request
# description shows up in site meta data, for search engines
description: |
  Your First PR helps you get started contributing to Open Source by showcasing great starter issues on Github and elsewhere.

# baseurl is used to format links in jekyll
baseurl: ""
# url is the sites full domain name
url: "https://yourfirstpr.github.io/"
# nice and clean blog URLs
permalink: "/blog/:title.html"
# name is used in the page header
name: Your First PR


## default site author info
# author is the name below posts
author: Charlotte Spencer
# author-url links this name to another page, twitter etc
author-url: https://twitter.com/charlotteis

## this prevents jekyll from building pages that are not website pages, but repo only pages
exclude: ["README.md", "CODEOFCONDUCT.md"]

## pagination settings
# set the total number of posts per page for the blog
paginate: 4
# have posts paged as: /blog/page2, /blog/page3 etc
paginate_path: "/blog/:num/"
